// sample_fields.dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:teamup/models/field_model.dart';

/// Lista de canchas de ejemplo para poblar la colección 'fields'
final List<FieldModel> sampleFields = [
  FieldModel(
    id: '',
    ownerId: 'Um0cQCPuiVO1HMg0KeKFiDpFXaY2',
    name: 'Cancha Central Park',
    zone: 'Vargas',
    lat: 40.785091,
    lng: -73.968285,
    surfaceType: 'Césped Sintético',
    pricePerHour: 50.0,
    imageUrl: 'https://res.cloudinary.com/drnkgp6xe/image/upload/v1748457262/directv_umdsxq.jpg',
    isActive: true,
    createdAt: DateTime.now(),
    availability: {
      'Monday': ['09:00', '11:00', '14:00'],
      'Wednesday': ['10:00', '16:00'],
      'Friday': ['18:00', '20:00'],
    },
    format: 'Fútbol 7',
    duration: 1.5,
    description: 'Cancha céntrica con iluminación nocturna',
    footwear: 'Botines de Césped Sintético',
    contact: '+1 234 567 890',
    hasDiscount: true,
    discountPercentage: 10.0,
    minPlayersToBook: 6,
  ),
  FieldModel(
    id: '',
    ownerId: 'Um0cQCPuiVO1HMg0KeKFiDpFXaY2',
    name: 'Cancha Riverside',
    zone: 'Miranda',
    lat: 40.800678,
    lng: -73.958509,
    surfaceType: 'Cemento',
    pricePerHour: 30.0,
    imageUrl: 'https://res.cloudinary.com/drnkgp6xe/image/upload/v1748457262/directv_umdsxq.jpg',
    isActive: true,
    createdAt: DateTime.now(),
    availability: {
      'Tuesday': ['08:00', '12:00'],
      'Thursday': ['15:00', '19:00'],
      'Sunday': ['10:00', '13:00'],
    },
    format: 'Fútbol 5',
    duration: 1.0,
    description: 'Canchas duras junto al río con vistas panorámicas',
    footwear: 'Zapatillas de Suela Lisa',
    contact: 'admin@riversidecourts.com',
    hasDiscount: false,
    discountPercentage: null,
    minPlayersToBook: 5,
  ),
  FieldModel(
    id: '',
    ownerId: 'Um0cQCPuiVO1HMg0KeKFiDpFXaY2',
    name: 'Estadio Playa Arena',
    zone: 'Distrito Capital',
    lat: 25.790654,
    lng: -80.130045,
    surfaceType: 'Césped Natural',
    pricePerHour: 75.0,
    imageUrl: 'https://res.cloudinary.com/drnkgp6xe/image/upload/v1748457262/directv_umdsxq.jpg',
    isActive: true,
    createdAt: DateTime.now(),
    availability: {
      'Wednesday': ['07:00', '09:00'],
      'Saturday': ['17:00', '21:00'],
    },
    format: 'Fútbol 11',
    duration: 2.0,
    description: 'Estadio frente al mar con césped natural',
    footwear: 'Botines de Césped Natural',
    contact: '+1 305 555 1234',
    hasDiscount: true,
    discountPercentage: 15.0,
    minPlayersToBook: 11,
  ),
  FieldModel(
    id: '',
    ownerId: 'Um0cQCPuiVO1HMg0KeKFiDpFXaY2',
    name: 'Cancha Montaña Verde',
    zone: 'Vargas',
    lat: 37.865101,
    lng: -119.538330,
    surfaceType: 'Cemento',
    pricePerHour: 45.0,
    imageUrl: 'https://res.cloudinary.com/drnkgp6xe/image/upload/v1748457262/directv_umdsxq.jpg',
    isActive: true,
    createdAt: DateTime.now(),
    availability: {
      'Monday': ['06:00', '08:00'],
      'Friday': ['18:00', '22:00'],
    },
    format: 'Fútbol 8',
    duration: 1.5,
    description: 'Ubicada en las colinas con vistas panorámicas',
    footwear: 'Botines de Suela Lisa',
    contact: 'contacto@montanaverdecourts.com',
    hasDiscount: false,
    discountPercentage: null,
    minPlayersToBook: 8,
  ),
  FieldModel(
    id: '',
    ownerId: 'Um0cQCPuiVO1HMg0KeKFiDpFXaY2',
    name: 'Arena Techno',
    zone: 'Miranda',
    lat: 34.052235,
    lng: -118.243683,
    surfaceType: 'Parquet',
    pricePerHour: 60.0,
    imageUrl: 'https://res.cloudinary.com/drnkgp6xe/image/upload/v1748457262/directv_umdsxq.jpg',
    isActive: true,
    createdAt: DateTime.now(),
    availability: {
      'Tuesday': ['10:00', '14:00'],
      'Thursday': ['16:00', '20:00'],
      'Sunday': ['12:00', '16:00'],
    },
    format: 'Pádel',
    duration: 1.0,
    description: 'Cancha indoor con parquet profesional',
    footwear: 'Zapatillas de Pista',
    contact: '+1 213 555 6789',
    hasDiscount: true,
    discountPercentage: 5.0,
    minPlayersToBook: 4,
  ),
];